JBM-684 resolve the issue: incompatible with DISTINCT
Expression #2 of ORDER BY clause is not in SELECT list,
references column 'jummp-biomodels.revision0_.revision_number'
which is not in SELECT list; this is incompatible with DISTINCT. Stacktrace follows:
java.sql.SQLException: Expression #2 of ORDER BY clause is not in SELECT list,
references column 'jummp-biomodels.revision0_.revision_number' which is not in
SELECT list; this is incompatible with DISTINCT