fix the following bug
2022-04-02 01:18:47,132 [localhost-startStop-1] ERROR context.GrailsContextLoaderListener  - Error initializing the application: org/codehaus/groovy/grails/plugins/jquery/JQueryConfig
java.lang.NoClassDefFoundError: org/codehaus/groovy/grails/plugins/jquery/JQueryConfig
	at JqueryGrailsPlugin$_closure1.doCall(JqueryGrailsPlugin.groovy:55)
	at grails.spring.BeanBuilder.invokeBeanDefiningClosure(BeanBuilder.java:754)
	at grails.spring.BeanBuilder.beans(BeanBuilder.java:584)
	at grails.spring.BeanBuilder.invokeMethod(BeanBuilder.java:527)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.ClassNotFoundException: org.codehaus.groovy.grails.plugins.jquery.JQueryConfig
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	... 8 more